# Generated by Django 4.0.3 on 2023-06-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_last_login_payment_extended_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='extended_date',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
