# Generated by Django 4.0.3 on 2023-06-05 05:23

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_phone_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[users.models.validate_ten_digits]),
        ),
    ]
