# Generated by Django 4.0.3 on 2023-06-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_payment_expiry_date_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='txnId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
