# Generated by Django 4.0.3 on 2023-06-09 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_payment_txnid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subscription'),
        ),
    ]
