# Generated by Django 4.0.3 on 2023-06-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('annual', 'annual'), ('quarter', 'quarter')], max_length=10),
        ),
    ]
