# Generated by Django 4.0.3 on 2023-06-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('Quarterly', 'Quarterly'), ('Annual', 'Annual'), ('Monthly', 'Monthly'), ('Semi-Annually', 'Semi-Annually')], max_length=20),
        ),
    ]
