label_data={
    1: {
        'top_bottom_margin': 3.378,
        'left_right_margin': 5.182,
        'cell_height': 289,
        'cell_width': 199.6,
        'rows': 1,
        'columns': 1,
        'hor_cell_gap':0,
        'ver_cell_gap':0,
    },
    2: {
        'top_bottom_margin': 4.877,
        'left_right_margin': 5.182,
        'cell_height': 143.6,
        'cell_width': 199.6,
        'rows': 2,
        'columns': 1,
        'hor_cell_gap':0,
        'ver_cell_gap':0,
    },
    4: {
        'top_bottom_margin': 9.5,
        'left_right_margin': 4.597,
        'cell_height': 99.1,
        'cell_width': 139,
        'rows': 2,
        'columns': 2,
        'hor_cell_gap':0,
        'ver_cell_gap':0,
    },
    6: {
        'top_bottom_margin': 8.788,
        'left_right_margin': 4.699,
        'cell_height': 99.1,
        'cell_width': 93.4,
        'rows': 3,
        'columns': 2,
        'hor_cell_gap':0,
        'ver_cell_gap':0,
    }
    ,
    8: {
        'top_bottom_margin': 12.979,
        'left_right_margin': 4.496,
        'cell_height': 67.7,
        'cell_width': 99.1,
        'rows': 4,
        'columns': 2,
        'hor_cell_gap':0,
        'ver_cell_gap':0,
    },
    10: {
        'top_bottom_margin': 5.994,
        'left_right_margin': 4.596,
        'cell_height': 57,
        'cell_width': 99.1,
        'rows': 5,
        'columns': 2,
        'hor_cell_gap':0,
        'ver_cell_gap':0,
    },
    12: {
        'top_bottom_margin': 7.62,
        'left_right_margin': 3.81,
        'cell_height': 44.15,
        'cell_width': 100,
        'rows': 6,
        'columns': 2,
        'hor_cell_gap':0,
        'ver_cell_gap':0,'font':'helvetica',
        'emphasis':'',  #'B'(Bold)/'I'(Italic)/'U'(Underlined)/''(Normal)
        'text-size':8,
        'text-color':"(0,0,0)"
    },
    14: {
        'top_bottom_margin': 15.088,
        'left_right_margin': 4.597,
        'cell_height': 38.4,
        'cell_width': 99.06,
        'rows': 7,
        'columns': 2,
        'hor_cell_gap':0,
        'ver_cell_gap':0,'font':'helvetica',
        'emphasis':'',  #'B'(Bold)/'I'(Italic)/'U'(Underlined)/''(Normal)
        'text-size':8,
        'text-color':"(0,0,0)"
    },
    16: {
        'top_bottom_margin': 12.5,
        'left_right_margin': 4.5,
        'cell_height': 33.9,
        'cell_width': 99.1,
        'rows': 8,
        'columns': 2,
        'hor_cell_gap':2.8,
        'ver_cell_gap':0.8/7,
        'font':'helvetica',
        'emphasis':'',  #'B'(Bold)/'I'(Italic)/'U'(Underlined)/''(Normal)
        'text-size':12,
        'text-color':"(255,123,150)"
    },
    18: {
        'top_bottom_margin': 8.788,
        'left_right_margin': 7.188,
        'cell_height': 46.6,
        'cell_width': 63.5,
        'rows': 6,
        'columns': 3,
        'hor_cell_gap':0,
        'ver_cell_gap':0,
    },
    20: {
        'top_bottom_margin': 8.788,
        'left_right_margin': 7.188,
        'cell_height': 28,
        'cell_width': 98,
        'rows': 10,
        'columns': 2,
        'hor_cell_gap':0,
        'ver_cell_gap':0,
    },
    21: {
        'top_bottom_margin': 15.088,
        'left_right_margin': 7.188,
        'cell_height': 38.1,
        'cell_width': 63.5,
        'rows': 7,
        'columns': 3,
        'hor_cell_gap':0,
        'ver_cell_gap':0,
    },
    24: {
        'top_bottom_margin': 12,
        'left_right_margin': 6,
        'cell_height': 34,
        'cell_width': 64,
        'rows': 8,
        'columns': 3,
        'hor_cell_gap':3,
        'ver_cell_gap':1/7,
    },
    30: {
        'top_bottom_margin': 2.499,
        'left_right_margin': 4.498,
        'cell_height': 39,
        'cell_width': 47.5,
        'rows': 6,
        'columns': 5,
        'hor_cell_gap':0,
        'ver_cell_gap':0,
    },
    33: {
        'top_bottom_margin': 8.89,
        'left_right_margin': 6.096,
        'cell_height': 66,
        'cell_width': 25.4,
        'rows': 11,
        'columns': 3,
        'hor_cell_gap':0,
        'ver_cell_gap':0,
    },
    40: {
        'top_bottom_margin': 0,
        'left_right_margin': 0,
        'cell_height': 29.7,
        'cell_width': 52.5,
        'rows': 10,
        'columns': 4,
        'hor_cell_gap':0,
        'ver_cell_gap':0,
    },
    48: {
        'top_bottom_margin': 21.336,
        'left_right_margin': 9.652,
        'cell_height': 21.1,
        'cell_width': 45.7,
        'rows': 12,
        'columns': 4,
        'hor_cell_gap':0,
        'ver_cell_gap':0,
    },
    56: {
        'top_bottom_margin': 9.144,
        'left_right_margin': 5.08,
        'cell_height': 20.1,
        'cell_width': 50,
        'rows': 14,
        'columns': 4,
        'hor_cell_gap':0,
        'ver_cell_gap':0,
    },
    65: {
        'top_bottom_margin': 10.1,
        'left_right_margin': 3,
        'cell_height': 21.2,
        'cell_width': 38.1,
        'rows': 13,
        'columns': 5,
        'hor_cell_gap':3,
        'ver_cell_gap':1.2/13,
    },
    84: {
        'top_bottom_margin': 15.875,
        'left_right_margin': 4.978,
        'cell_height': 11,
        'cell_width': 46,
        'rows': 21,
        'columns': 4,
        'hor_cell_gap':0,
        'ver_cell_gap':0,
    }
}

keys=[]

# keys list 
for key in label_data.keys():
    keys.append(key)

# Remove unnecessary attributes from each dictionary
# for key in label_data:
#     label_data[key] = {'rows': label_data[key]['rows'], 'columns': label_data[key]['columns']}