# Generated by Django 4.0.3 on 2023-05-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StickerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_type', models.CharField(max_length=50)),
                ('per_sheet_dropdown', models.IntegerField()),
                ('rows_dropdown', models.IntegerField(blank=True, null=True)),
                ('columns_dropdown', models.IntegerField(blank=True, null=True)),
                ('csv', models.FileField(upload_to='csv_files/')),
            ],
        ),
    ]
