# Generated by Django 4.0.3 on 2023-06-15 06:37

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0019_alter_payment_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font', models.CharField(choices=[('Courier', 'Courier (fixed-width)'), ('Helvetica', 'Helvetica or Arial (sans serif)'), ('Times', 'Times (serif)'), ('Symbol', 'Symbol (symbolic)'), ('ZapfDingbats', 'ZapfDingbats (symbolic)')], default='Helvetica', max_length=20)),
                ('emphasis', models.CharField(choices=[('', 'Regular'), ('B', 'Bold'), ('I', 'Italic'), ('U', 'Underline')], default='', max_length=1)),
                ('text_size', models.IntegerField(default=8)),
                ('text_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
