# Generated by Django 4.0.3 on 2023-06-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelPrintApp', '0004_alter_labelconfig_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelconfig',
            name='font',
            field=models.CharField(choices=[('Courier', 'Courier (fixed-width)'), ('Helvetica', 'Helvetica or Arial (sans serif)'), ('Times', 'Times (serif)')], default='helvetica', max_length=20),
        ),
    ]
