# Generated by Django 4.0.3 on 2023-06-18 11:39

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelPrintApp', '0005_alter_labelconfig_font'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labelconfig',
            old_name='emphasis',
            new_name='emphasis_line1',
        ),
        migrations.RenameField(
            model_name='labelconfig',
            old_name='font',
            new_name='font_line1',
        ),
        migrations.RenameField(
            model_name='labelconfig',
            old_name='text_color',
            new_name='text_color_line1',
        ),
        migrations.RenameField(
            model_name='labelconfig',
            old_name='text_size',
            new_name='text_size_line1',
        ),
        migrations.AddField(
            model_name='labelconfig',
            name='emphasis_line2',
            field=models.CharField(blank=True, choices=[('', 'Regular'), ('B', 'Bold'), ('I', 'Italic'), ('U', 'Underline')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='labelconfig',
            name='emphasis_line3',
            field=models.CharField(blank=True, choices=[('', 'Regular'), ('B', 'Bold'), ('I', 'Italic'), ('U', 'Underline')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='labelconfig',
            name='emphasis_line4',
            field=models.CharField(blank=True, choices=[('', 'Regular'), ('B', 'Bold'), ('I', 'Italic'), ('U', 'Underline')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='labelconfig',
            name='font_line2',
            field=models.CharField(choices=[('Courier', 'Courier (fixed-width)'), ('Helvetica', 'Helvetica or Arial (sans serif)'), ('Times', 'Times (serif)')], default='helvetica', max_length=20),
        ),
        migrations.AddField(
            model_name='labelconfig',
            name='font_line3',
            field=models.CharField(choices=[('Courier', 'Courier (fixed-width)'), ('Helvetica', 'Helvetica or Arial (sans serif)'), ('Times', 'Times (serif)')], default='helvetica', max_length=20),
        ),
        migrations.AddField(
            model_name='labelconfig',
            name='font_line4',
            field=models.CharField(choices=[('Courier', 'Courier (fixed-width)'), ('Helvetica', 'Helvetica or Arial (sans serif)'), ('Times', 'Times (serif)')], default='helvetica', max_length=20),
        ),
        migrations.AddField(
            model_name='labelconfig',
            name='text_color_line2',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='labelconfig',
            name='text_color_line3',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='labelconfig',
            name='text_color_line4',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='labelconfig',
            name='text_size_line2',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='labelconfig',
            name='text_size_line3',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='labelconfig',
            name='text_size_line4',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
